config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'
  devise_for :users,
              :controllers => {
                :omniauth_callbacks => 'omniauth_callbacks',
                :registrations => "users/registrations",
                invitations: "users/invitations"
              }

  devise_scope :user do
    get 'users/sign_out', :to => "devise/sessions#destroy"
  end


  root to: 'pages#home'
  get '/about', to: "pages#about"
  get '/terms-and-conditions', to: "pages#terms_and_conditions"
  get '/thank-you-for-the-sign-up', :to => "pages#sign_up_thank_you"
  get '/prelaunch_thank_you', :to => "pages#prelaunch_thank_you"
  get '/robots.:format' => 'pages#robots'
  get '/coming-soon' => 'pages#coming_soon'
  get '/apartments/search', :to => 'apartments#search', :defaults => { :format => 'js' }
  post '/apartments/:id/thank', :to => 'apartments#thank', :defaults => {:format => 'json'}

  resources :amenities
  resources :apartments
  resources :coworking_spaces
  resources :feedbacks
  resources :cities

  # namespace :admin do
  # 	get 'dashboard', :to => 'pages#dashboard'
  #   resources :amenities
  # 	resources :apartments
  # 	resources :coworking_spaces
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_admin_navbar.html.erb
<div class="row">
    <!-- uncomment code for absolute positioning tweek see top comment in css -->
    <!-- <div class="absolute-wrapper"> </div> -->
    <!-- Menu -->
    <div class="side-menu">

    <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <div class="brand-wrapper">
            <!-- Hamburger -->
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Brand -->
            <div class="brand-name-wrapper">
                <%= link_to "Belooga", root_path, :class => 'navbar-brand'%>
            </div>

            <!-- Search -->
            <a data-toggle="collapse" href="#search" class="btn btn-default" id="search-trigger">
                <span class="glyphicon glyphicon-search"></span>
            </a>

            <!-- Search body -->
            <div id="search" class="panel-collapse collapse">
                <div class="panel-body">
                    <form class="navbar-form" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default "><span class="glyphicon glyphicon-ok"></span></button>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- Main Menu -->
    <div class="side-menu-container">
        <ul class="nav navbar-nav">
            <!-- Dropdown-->
            <li class="panel panel-default" id="dropdown">
                <a data-toggle="collapse" href="#dropdown-apartments">
                    <span class="glyphicon glyphicon-book"></span> Apartments <span class="caret"></span>
                </a>
                <!-- Dropdown level 1 -->
                <div id="dropdown-apartments" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul class="nav navbar-nav">
                            <li><%= link_to "All the Apartments", admin_apartments_path %></li>
                            <li><%= link_to "Create new", new_admin_apartment_path %></li>
                        </ul>
                    </div>
                </div>
            </li>
            <!-- Dropdown end -->
             <!-- Dropdown-->
            <li class="panel panel-default" id="dropdown">
                <a data-toggle="collapse" href="#dropdown-amenities">
                    <span class="glyphicon glyphicon-book"></span> Amenities <span class="caret"></span>
                </a>
                <!-- Dropdown level 1 -->
                <div id="dropdown-amenities" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul class="nav navbar-nav">
                            <li><%= link_to "All the Amenities", admin_amenities_path %></li>
                            <li><%= link_to "Create new", new_admin_amenity_path %></li>
                        </ul>
                    </div>
                </div>
            </li>
            <!-- Dropdown end -->
            <li class="panel panel-default" id="dropdown">
                <a data-toggle="collapse" href="#dropdown-coworking">
                    <span class="glyphicon glyphicon-book"></span> Coworking Spaces <span class="caret"></span>
                </a>
                <!-- Dropdown level 1 -->
                <div id="dropdown-coworking" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul class="nav navbar-nav">
                            <li><%= link_to "All the Coworking Spaces", admin_coworking_spaces_path %></li>
                            <li><%= link_to "Create new", new_admin_coworking_space_path %></li>
                        </ul>
                    </div>
                </div>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="glyphicon glyphicon-off"></span>Log Out
              <% end %>
            </li>
            <!-- Dropdown-->
        </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

</div>
</div>

app/views/shared/_footer.html.erb
<footer id="myFooter" style="position: relative;">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 hide-768">
                <h2 class="logo"><a href="#"> <img height=100 src="https://s3.eu-west-2.amazonaws.com/belooga/Images/belooga-no-background.png"> </a></h2>
            </div>
            <div class="col-lg-2 col-sm-3">
                <h5>Get started</h5>
                <ul>
                    <li><a href="<%= root_path %>">Home</a></li>
                    <!-- <li><a href="<%= new_user_registration_path %>">Sign up</a></li> -->
                </ul>
            </div>
            <div class="col-lg-2 col-sm-3">
                <h5>About us</h5>
                <ul>
                    <!-- <li><a href="<%= about_path %>">About</a></li> -->
                    <li><a href="<%= new_feedback_path %>">Contact</a></li>
                    <li><a href="<%= terms_and_conditions_path%>"> T&C </a></li>
                </ul>
            </div>
            <div class="col-lg-5 col-sm-6">
                <div class="social-networks">
                    <a href="https://www.twitter.com/belooga_" class="twitter"><i class="fa fa-twitter"></i></a>
                    <a href="https://www.facebook.com/beloogaapp" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="https://www.instagram.com/belooga_" class="instagram"><i class="fa fa-instagram"></i></a>
                </div>
                <%= link_to "Contact", new_feedback_path, :class => 'btn btn-default'%>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <p>Copyright © <%= Date.current.year %> Belooga </p>
    </div>
    <div class="made-with-love">
        <p>Made with <i class="fa fa-heart" aria-hidden="true"></i> by Nomads for Nomads</p>
    </div>
</footer>

app/views/shared/_ga.html.erb
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-99124078-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-99124078-1');
</script>

app/views/shared/_list_container.html.erb
<div class="container-fluid list-container">
	<% if @apartments != []%>
		<% @apartments.each_with_index do |a, index| %>
			<a href="<%= apartment_path(a)%>">
				<div class="card apartment-card shadow">
				   <% if a.home_owner %> 
            	     <img style="height:100px; width: 100px; position: absolute; bottom: 0; right: 0;" src="https://farm5.staticflickr.com/4398/36296947521_2d6f00d98c_o.png"> 
                  <% end %>
				  <% if a.wifi_speed %>
				  	<img src="<%= a.wifi_speed.badge%>" class="rounded-circle wifi-badge shadow">
				  <% end %>
				  <div class="row">
				  	<div class="col-md-5 image-box">
				  		<% if a.pictures != [] %>
				  			<% if a.pictures.first.direct_uri %>
				  				<div style="background: url(<%= a.pictures.first.direct_uri %>);" class="apartment-thumb"></div>
				  			<% else %>
				  				<div style="background: url(<%= a.pictures.first.image.url %>);" class="apartment-thumb"></div>
				  			<% end %>
				  		<% else %>
				  			<div style="background: url(//s3.eu-west-2.amazonaws.com/belooga/Images/image-missing.png);" class="apartment-thumb"></div>
				  		<% end %>
				  	</div>
				  	<div class="col-md-7 text-box">
				  		<h4 class="apartment-name"><%= a.name %></h4>
				  		<span class="apartment-address"><%= a.address %></span>
				  		<h5><span class="badge badge-pill badge-primary" style="margin-top: 15px; text-transform: none;"><%= a.avg_price%>$/month</span></h5>
				  		<ul class="amenities-list">
				  			<% a.amenities.each do |amenity| %>
								<li> <span> <%= amenity.name %> </span> <i class="<%= amenity.icon %>" aria-hidden="true"></i></li>
							<% end %>
				  		</ul>
				  	</div>
				  </div>
				</div>
			</a>
		<% end %>
	<% else %>
		<div class="empty-list text-center" style="margin-top: 30px;">
			<h2 style="text-transform: capitalize;"> OOPS! Looks like there are no apartments matching your search results</h2>
			<script>
				$.ajax({
				  url: "http://api.giphy.com/v1/gifs/search?q=oops&api_key=dc6zaTOxFJmzC",
				  success: function(data){
				  	let gifs = data.data;
				  	var random = Math.floor(Math.random()*gifs.length);
				  	let gifUrl = gifs[random].images.original.url;
				  	console.log(gifUrl);
				  	let html = "<img src="+gifUrl+" style='height: 400px; width:400px;'>"
				  	$('.empty-list').append(html);
				  	console.log(data.data.length);
				  }
				}).done(function() {
				  console.log('done');
				});
			</script>
		</div>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<% if cookies[:has_account] %>
    <nav class="navbar navbar-toggleable-md navbar-inverse belooga-navbar">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">
            <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/belooga-beta.png" style="height: 100px;">
        </a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <!--         <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
            </ul> -->
            <ul class="navbar-nav ml-auto">
                <% if current_user && current_user.admin? %>
                    <%= link_to "admin", "/backoffice", class: "nav-link" %>
                <% end %>
                <li class="nav-item active">
                    <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= about_path %>">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= new_apartment_path %>">Add A Home</a>
                </li>
                <% if current_user %>
                    <li class="nav-item">
                        <% if current_user.picture %>
                            <img src="<%=current_user.picture.image.url%>" alt="user-profile-picture" class="rounded-circle" style="height: 50px; width: 50px;">
                        <% end %>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= current_user.name%>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'dropdown-item') %>
                        </div>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to('Login', new_user_session_path, :class => 'nav-link') %>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>
<% elsif !current_user && Time.now < "2017/08/01" %>
    <nav class="navbar navbar-toggleable-md navbar-inverse belooga-navbar text-center">
        <a class="navbar-brand" href="<%= root_path %>" style="margin: auto;">
            <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/belooga-beta.png" style="height: 100px;">
        </a>
    </nav>
<% else %>
    <nav class="navbar navbar-toggleable-md navbar-inverse belooga-navbar">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">
            <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/belooga-beta.png" style="height: 100px;">
        </a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <!--         <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
            </ul> -->
            <ul class="navbar-nav ml-auto">
                <% if current_user && current_user.admin? %>
                    <%= link_to "admin", "/backoffice", class: "nav-link" %>
                <% end %>
                <li class="nav-item active">
                    <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= about_path %>">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= new_apartment_path %>">Add A Home</a>
                </li>
                <% if current_user %>
                    <li class="nav-item">
                        <% if current_user.picture %>
                            <img src="<%=current_user.picture.image.url%>" alt="user-profile-picture" class="rounded-circle" style="height: 50px; width: 50px;">
                        <% end %>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= current_user.name%>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'dropdown-item') %>
                        </div>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to('Login', new_user_session_path, :class => 'nav-link') %>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>
<% end %>