config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'
  devise_for :users,
              :controllers => {
                :omniauth_callbacks => 'omniauth_callbacks',
                :registrations => "users/registrations",
                invitations: "users/invitations"
              }

  devise_scope :user do
    get 'users/sign_out', :to => "devise/sessions#destroy"
  end


  root to: 'pages#home'
  get '/about', to: "pages#about"
  get '/terms-and-conditions', to: "pages#terms_and_conditions"
  get '/thank-you-for-the-sign-up', :to => "pages#sign_up_thank_you"
  get '/prelaunch_thank_you', :to => "pages#prelaunch_thank_you"
  get '/robots.:format' => 'pages#robots'
  get '/coming-soon' => 'pages#coming_soon'
  get '/apartments/search', :to => 'apartments#search', :defaults => { :format => 'js' }
  post '/apartments/:id/thank', :to => 'apartments#thank', :defaults => {:format => 'json'}

  resources :amenities
  resources :apartments
  resources :coworking_spaces
  resources :feedbacks
  resources :cities

  # namespace :admin do
  # 	get 'dashboard', :to => 'pages#dashboard'
  #   resources :amenities
  # 	resources :apartments
  # 	resources :coworking_spaces
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_coming_soon.html.erb
<% content_for :head do %>
  <title>Belooga - Digital Nomad Accommdations Made Easy</title>
  <meta name="description" content="Belooga is the first online platform that will help digital nomads in finding a place where to live"/>
  <meta name="keywords" content="Accommdation for digital nomads, digital nomad accommdation, digital nomad apartment"/>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.countdown/2.2.0/jquery.countdown.js"></script>
  <style>
    html, body{
      height: 100%;
    }

    .login-btn{
      text-transform: none; 
      color: #1a3438; 
      background-color: transparent; 
      border-radius: 20px; 
      padding-left: 15px; 
      padding-right: 15px;
      border: 1px solid #0275d8;
      position: absolute;
      z-index: 10;
      right: 15px;
      top: 15px;
      padding-top: 3px;
      padding-bottom: 3px;
    }

    .login-btn:hover{
      text-decoration: none;
      background-color: #0275d8;
      color: white;
    }

    .prelaunch-container .prelaunch-container-background{
      background-image: url(https://images.unsplash.com/photo-1452457779869-0a9ebbbdee99);
      background-size: cover;
      filter: blur(2px);
      -webkit-filter: blur(2px);
      height: 100%;
      width: 100%;
      z-index: 1;
      background-position
    }

    .subtitle{
      font-size: 19px;
    }

    .prelaunch-container{
      height: 100%;
    }

    @media screen and (max-width: 768px) {

    }

    .prelaunch-container img{
      top: 30px;
      left: 0;
      position: absolute;
      margin: auto;
      right: 0;
      z-index: 2;
      padding: 0 10px;
      height: 150px;
    }

    .prelaunch-container h1{
      text-transform: none;
    }

    .content {
      background: rgba(255, 255, 255, 0.55);
      border-radius: 3px;
      box-shadow: 0 1px 5px rgba(0, 0, 0, 0.25);
      top: 200px;
      left: 0;
      position: absolute;
      margin: auto;
      right: 0;
      z-index: 2;
    }

    .social-share-btns{
      background: white;
      position: absolute;
      z-index: 2;
      bottom: 0;
      width: 100%;
      height: 50px;
    }

    .container-fluid{
      padding: 0;
    }

    @media screen and (max-width: 768px) {
      .content{
        top: 130px;
        /*background: transparent;
        border: none;
        box-shadow: none;*/
        margin-top: 30px;
        padding-top: 0;
      }

      .prelaunch-container h1{
        font-size: 28px
      }      

      .prelaunch-container img{
        height: 100px;
      }
    }

    .navbar.navbar-toggleable-md.navbar-inverse.belooga-navbar{
      display: none;
    }

    #myFooter{
      display: none;
    }
    .ml-button-iframe {
        background-color: transparent !important;
        border: 0px none transparent!important;
        overflow: hidden !important;
        position: fixed !important;
        visibility: visible !important;
        margin: 0px !important;
        padding: 0px !important;
        left: 0px !important;
        top: 0px !important;
        width: 100% !important;
        height: 100% !important;
        z-index: 999999 !important;
        display: none;
    }

    .ml-subscribe-button{
      font-family: 'Raleway', sans-serif !important;
    }

  </style>
<% end %>
<div class="container-fluid prelaunch-container">
  <a class="login-btn" href="<%= new_user_session_path %>">Log In</a>
  <div class="row">
    <div class="col-12 text-center">
      <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/belooga-beta.png">
    </div>
  </div>
  <div class="prelaunch-container-background"></div>
  <div class="row">
    <div class="col-md-6 offset-md-3 content padding">
      <div class="row text-center padding-top">
        <h1> Effortless housing for Digital Nomads.</h1>
      </div>
      <div class="row text-center padding-15">
        <span class="subtitle"> If each one of us would share the homes they stayed at around the world, things would get much easier.</span>
      </div>
      <div class="row mailer-lite-btn-container text-center padding-top">
        <form id="mlb2-5379735" action="//app.mailerlite.com/webforms/popup/m9q1q8" data-code="m9q1q8" data-id="456077" target="_blank" style="margin: auto;">
          <div class="button-preview">
              <button type="submit" class="ml-subscribe-button btn btn-primary padding-15 shadow" style="font-size: 21px; white-space: normal;">Let me know when it goes live</button>
          </div>
        </form>
        <script type="text/javascript" src="//static.mailerlite.com/js/w/button.min.js?v1f0baea18b848a8ab8e485e9a1acc285"></script>
      </div>
      <div class="row padding-top text-center center-block">
        <a href="<%= new_apartment_path %>" class="btn btn-primary padding-15 shadow" style="font-size: 21px; white-space: normal; margin: auto;"> Let me add a home and get early bird access </a>
      </div>
      <div class="row text-center padding-top">
        <div class="addthis_inline_share_toolbox_o5pu" data-url="http://belooga.co" data-title="Sign Up On Belooga" data-description="I just found out about Belooga. Accommodation for Digital Nomads made easy, sign up to get early bird access!" data-media="https://s3.eu-west-2.amazonaws.com/belooga/Images/belooga-no-background.png" style="margin: auto;"></div>
      </div>
      <div class="row text-center">
        <span style="margin: auto;"> - Spread the word - </span>
      </div>
    </div>
  </div>
</div>

app/views/pages/_normal_home_page.html.erb
<% content_for :head do %>
    <title>Belooga - Digital Nomad Accommodations Made Easy</title>
    <meta name="description" content="Belooga is the first online platform that will help digital nomads in finding a place where to live"/>
    <meta name="keywords" content="Accommodation for digital nomads, digital nomad accommodation, digital nomad apartment"/>
  <% end %>
  <div class="container-fluid hero-container home-hero parallax">
    <div class="container hero-content">
      <div class="row">
        <div class="col-12">
          <% if current_user %>
            <h1> WELCOME BACK <%= current_user.name %></h1>
          <% else %>
            <h1 class="text-center hero-header">Accommodation FOR DIGITAL NOMADS MADE EASY WITH <span class="belooga-header">BELOOGA!</span></h1>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class=" col-12 btn-stripe">
          <div class="row">
            <div class="col-lg-3 offset-lg-2 col-md-12">
              <button type="button" class="btn btn-hg btn-white-border" data-toggle="modal" data-target="#city-modal">
                <i class="fa fa-search" aria-hidden="true"></i> Browse Homes
              </button>
            </div>
            <div class="col-lg-3 offset-lg-2 col-md-12">
              <%= link_to new_apartment_path , :class => "btn btn-hg btn-primary" do %>
                <i class="fa fa-plus" aria-hidden="true"></i> Add A Home
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="overlay"></div>
  </div>

  <div class="container-fluid top-picks-container page-section">
    <h2 class='text-center page-section-header'> Latest Added Homes </h2>
      <div class="row">
        <% 6.times do |i| %>
          <% if @apartments[i].pictures != [] %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="card top-picks-card">
                <% if  @apartments[i].pictures.first.direct_uri %>
                  <div class="top-picks-img" style="background-image: url(<%= @apartments[i].pictures.first.direct_uri %>);"></div>
                <% else %>
                  <div class="top-picks-img" style="background-image: url(<%= @apartments[i].pictures.first.image.url%>);"></div>
                <% end %>
                <h3 class="text-center"> <%= @apartments[i].city.name if @apartments[i].city.name %> </h3>
                <div class="cta-holder text-center">
                  <a href="<%= apartment_path(@apartments[i])%>">
                    <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>
                  </a>
                </div>
                <div class="apt-meta text-center">
                  <span> <%= @apartments[i].name.capitalize %> </span><br>
                  <span> <%= @apartments[i].avg_price %>$/month </span>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
  <div class="container all-cities-container page-section">
    <h4 class="text-center page-section-header"> Our spotters have added homes in <%= @cities.length %> different cities, and counting. </h2>
    <div class="row padding-top">
      <% @cities[0..11].each do |city| %>
        <div class="col-lg-4 text-center padding-bottom">
          <a href="<%= apartments_path(city: city)%>" style="font-size: 19px; color: #353535;"> <span> <%= city.capitalize %> </span> </a>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container-fluid page-section made-easy-container">
    <h2 class="text-center"> Why Belooga </h2>
    <div class="overlay"></div>
  </div>
  <div class="info-cards card-deck">
    <div class="col-lg-4 col-md-12 text-center">
      <div class="card text-center invisible">
        <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/community.png" class="card-img-top">
        <div class="card-block">
          <h4 class="card-title">Community</h4>
          <p class="card-text">Digital nomad? Backpacker? Perpetual traveler? Then, Belooga is made for You! If you Stay in one place too long for normal hotels And too short for normal term rentals, Belooga is for you!</p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-12 text-center">
      <div class="card text-center invisible">
        <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/upload.png" class="card-img-top">
        <div class="card-block">
          <h4 class="card-title">Help Others</h4>
          <p class="card-text">Did you Just find A hidden gem in Chiang Mai? Or perhaps a beautiful villa In Bali? Let the community know by spotting the place on Belooga! The community will never be able to thank you enough!</p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-12 text-center">
      <div class="card text-center invisible">
        <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/search.png" class="card-img-top">
        <div class="card-block">
          <h4 class="card-title">Accommodation Made Easy</h4>
          <p class="card-text">About to move to Cran Canaria? Take a look at what other nomads have spotted on Belooga and what they thought of it. Get an idea of the wifi speed in the apartments and get the contact of the landlord!</p>
        </div>
      </div>
    </div>
  </div>

app/views/pages/about.html.erb
<% content_for :head do %>
  <title>Belooga - Digital Nomad Accommdations Made Easy</title>
  <meta name="description" content="Belooga is the first online platform that will help digital nomads in finding a place where to live"/>
  <meta name="keywords" content="Accommdation for digital nomads, digital nomad accommdation, digital nomad apartment"/>
<% end %>

<div class="container-fluid parallax half-page-hero about-hero">
  <div class="container hero-content">
    <div class="row">
      <div class="col-12">
        <h1> ABOUT BELOOGA!</h1>
      </div>
    </div>
  </div>
  <div class="overlay"></div>
</div>
<div class="container abount-container">
  <div class="row">
    <div class="col-md-9 offset-md-1 shadow about-text text-center">
      <p>
        As a <strong>Digital Nomad</strong>, you spend a good portion of your life looking for accommodation. 
      </p>
      <p>
        Sometimes it’s easy, and sometimes it’s not.
      </p>
      <p>
        Looking for the best prices, coolest locations and <strong>fastest wifi </strong>takes some serious time and dedication. 
        But what if you could <strong>tap into the knowledge of nomads</strong> all over the world?
      </p>
      <p>
        Belooga makes finding accommodation easy!
      </p>
      <p>
        Airbnb can be great in some cities, in others you <strong>spend hours</strong> trawling through facebook groups or driving through town on your rented scooter.
      </p>
      <p>
        Belooga makes <strong>finding your next home easy</strong>, with landlord contact details, wifi speeds, and places to work from closeby.
        Discover accommodation tried and tested by the digital nomad community, and contribute to the platform!
      </p>
      <p>
        Belooga was born out of <strong>our own</strong> experiences as digital nomads. We understand how important it is to find somewhere you can work productively, have all your creature comforts, and connect with your community.
      </p>
      <p>
        We wanted to make life easier so we can all <strong>spend more time enjoying the journey</strong>, rather than planning it.
        Meet the team behind Belooga and get in touch if you have any suggestions, questions or if you want to catch up over a coffee or beer somewhere in the world.
      </p>
      <div class="row meet-the-team-row">
        <div class="col-12 text-center" style="padding-bottom: 30px;">
          <h4> MEET THE TEAM</h4>
        </div>
        <div class="col-lg-4 text-center">
          <div class="row">
            <div class="col-12 meet-the-team-section">
              <a href="https://twitter.com/andrea_munches">
                <div class="meet-the-team-pic" style="background-image: url(https://s3.eu-west-2.amazonaws.com/belooga/Images/andrea-belooga.jpg); background-size: cover; height: 100px; width: 100px; border-radius: 50%; margin: auto;">  
                </div>
              </a>
            </div>
            <div class="col-12 text-center meet-the-team-section">
              <h6> Andrea </h6>
            </div>
            <div class="col-12 meet-the-team-section team-bio">
              Southern Italian. Traveler. Footballer. Boulderer. Serial Eater. He travels to locations where the sun shines and the food makes his Mamma proud. Web developer, creative by definition and digital entrepreneur.
            </div>
          </div>
        </div>
        <div class="col-lg-4 text-center">
          <div class="row">
            <div class="col-12 meet-the-team-section">
              <a href="https://ninahoeberichts.com">
                <div class="meet-the-team-pic" style="background-image: url(https://s3.eu-west-2.amazonaws.com/belooga/Images/IMG_4092_crop.jpg); background-size: cover; height: 100px; width: 100px; border-radius: 50%; margin: auto;">  
                </div>
              </a>
            </div>
            <div class="col-12 text-center meet-the-team-section">
              <h6> Nina </h6>
            </div>
            <div class="col-12 meet-the-team-section team-bio">
              Half-asian Dutchie. Globetrotter. Singer & Songwriter. Foodie. Writer. UX Strategist and Designer, creating the best user experiences imaginable..
            </div>
          </div>
        </div>
        <div class="col-lg-4 text-center">
          <div class="row">
            <div class="col-12 meet-the-team-section">
              <div class="meet-the-team-pic" style="background-image: url(https://s3.eu-west-2.amazonaws.com/belooga/Images/rosanna-belooga.jpg); background-size: cover; height: 100px; width: 100px; border-radius: 50%; margin: auto;">  
              </div>
            </div>
            <div class="col-12 text-center meet-the-team-section">
              <h6> Rosanna </h6>
            </div>
            <div class="col-12 text-center meet-the-team-section team-bio">
              Dutch/ Portuguese wifi junkie, find her wherever the sun DOES shine and try to beat her at Fussball if you dare. Favourite food: All of it. Ah right, and she's been an Online Marketer for 8 years, nomadic since May 2015.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'normal_home_page' %>

app/views/pages/prelaunch_thank_you.html.erb
<% content_for :head do %>
  <title>Belooga - Digital Nomad Accommdations Made Easy</title>
  <meta name="description" content="Belooga is the first online platform that will help digital nomads in finding a place where to live"/>
  <meta name="keywords" content="Accommdation for digital nomads, digital nomad accommdation, digital nomad apartment"/>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.countdown/2.2.0/jquery.countdown.js"></script>
<% end %>
<div class="contaier padding">
	<div class="row">
		<div class="col-md-12 text-center padding-bottom">
			<i class="fa fa-rocket" aria-hidden="true" style="font-size: 100px;"></i>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-center padding-bottom">
			<h1>Thank You!</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-center padding-bottom">
			<span><h5 style="text-transform: none;">We're reviewing the home you posted and will send the invitation over very soon!</h5></span>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-center padding-bottom">
			<span class="padding-bottom"> In the meanwhile, share the love for Belooga on your social media! </span><br>
			<div class="addthis_inline_share_toolbox_o5pu padding-top" data-url="http://belooga.co" data-title="Belooga Early Bird Access" data-description="I've just added a home on Belooga to get early bird access. Why don't you try as well? Accommdation for Digital Nomads has never been this easy." data-media="https://s3.eu-west-2.amazonaws.com/belooga/Images/belooga-no-background.png"></div>
		</div>
	</div>
</div>

<script type="text/javascript">
	var addthis_share = addthis_share || {}
	addthis_share = {
		passthrough : {
			twitter: {
				via: "belooga_",
				text: "I've just added a home on Belooga to get early bird access. Why don't you try as well?",
				url: "http://belooga.co",
				hashtags: "beloogalaunch"
			}
		}
	}
</script>

app/views/pages/robot.text.erb
<% if Rails.env.production? %>
  User-Agent: *
  Allow: /
  Disallow: /admin
<% else %>
  User-Agent: *
  Disallow: /
<% end %>

app/views/pages/sign_up_thank_you.html.erb
<% content_for :head do %>
  <title>Belooga - Digital Nomad Accommdations Made Easy</title>
  <meta name="description" content="Belooga is the first online platform that will help digital nomads in finding a place where to live"/>
  <meta name="keywords" content="Accommdation for digital nomads, digital nomad accommdation, digital nomad apartment"/>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.countdown/2.2.0/jquery.countdown.js"></script>
  <style>
    .navbar.navbar-toggleable-md.navbar-inverse.belooga-navbar{
      display: none;
    }
  </style>
<% end %>
<div class="container-fluid belooga-navbar parallax thank-you-hero">
  <div class="container hero-content">
    <div class="row">
      <div class="col-12">
        <h1> Hi <%= current_user.name %>, thank you for joining the Belooga family!</h1>
        <% if User.all.length < 100 %>
        <h2 class="cta"> You are one of our early adopters! Here for you the Founding Member badge, Congrats!</h2>
        <img style="height: 100px; width: auto;"src="https://s3.eu-west-2.amazonaws.com/belooga/Images/founding-member-badge.png">
        <% end %>
      </div>
    </div>
  </div>
  <div class="overlay"></div>
</div>
<div class="info-cards card-deck">
  <div class="col-lg-4 col-md-12 text-center">
    <div class="card text-center">
      <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/one.png" class="card-img-top">
      <div class="card-block">
        <h4 class="card-title">Spot</h4>
        <p class="card-text">Did you just spot a hidden gem in Koh Lanta? Upload it to the Belooga and let the community know!</p>
        <a href="<%= new_apartment_path %>" class="btn btn-default thank-you-btn" style="width: 150px;">Start Spotting</a>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-12 text-center">
    <div class="card">
      <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/two.png" class="card-img-top">
      <div class="card-block">
        <h4 class="card-title">Search</h4>
        <p class="card-text">Moving to Lisbon? Check if someone has spotted anything around there. You might be few clicks away from your dream home!</p>
        <a href="<%= apartments_path %>"class="btn btn-default thank-you-btn" style="width: 150px;">Start Searching</a>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-12 text-center">
    <div class="card">
      <img src="//s3.eu-west-2.amazonaws.com/belooga/Images/three.png" class="card-img-top">
      <div class="card-block">
        <h4 class="card-title">Share</h4>
        <p class="card-text">Share Belooga with your friends and help us spreading the word. We want to make accommdations hunting for digital nomads as easy as it can get!</p>
        <span class="thank-you-btn"><div class="addthis_inline_share_toolbox_o5pu"></div></span>
      </div>
    </div>
  </div>
</div>