config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'
  devise_for :users,
              :controllers => {
                :omniauth_callbacks => 'omniauth_callbacks',
                :registrations => "users/registrations",
                invitations: "users/invitations"
              }

  devise_scope :user do
    get 'users/sign_out', :to => "devise/sessions#destroy"
  end


  root to: 'pages#home'
  get '/about', to: "pages#about"
  get '/terms-and-conditions', to: "pages#terms_and_conditions"
  get '/thank-you-for-the-sign-up', :to => "pages#sign_up_thank_you"
  get '/prelaunch_thank_you', :to => "pages#prelaunch_thank_you"
  get '/robots.:format' => 'pages#robots'
  get '/coming-soon' => 'pages#coming_soon'
  get '/apartments/search', :to => 'apartments#search', :defaults => { :format => 'js' }
  post '/apartments/:id/thank', :to => 'apartments#thank', :defaults => {:format => 'json'}

  resources :amenities
  resources :apartments
  resources :coworking_spaces
  resources :feedbacks
  resources :cities

  # namespace :admin do
  # 	get 'dashboard', :to => 'pages#dashboard'
  #   resources :amenities
  # 	resources :apartments
  # 	resources :coworking_spaces
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
	def new
		@feedback = Feedback.new
	end

	def create
		@feedback = Feedback.create(feedback_params)
		respond_to do |format|
			if @feedback.save
				from = Email.new(email: @feedback.email)
			    to = Email.new(email: "andrea.rocca3@gmail.com")
			    sender_name = @feedback.name || ""
			    subject = "[Belooga Feedback][#{@feedback.feedback_type}] New message from #{sender_name}"
			    content = Content.new(type: "text/html", value: @feedback.body)
			    mail = SendGrid::Mail.new(from, subject, to, content)
			    mail.template_id = '82ff248c-3492-481e-b8dc-6658c78db90d'
			    sg = SendGrid::API.new(api_key: ENV["SENDGRID_API_KEY"])
			    response = sg.client.mail._("send").post(request_body: mail.to_json)
			    puts response.status_code
			    puts response.body
			    puts response.headers
			end
			format.html { redirect_to root_path, notice: 'Your feedback was submitted! You will hear from us very soon' }
		end
	end


	private
	  def feedback_params
	    params.require(:feedback).permit(:name, :email, :body, :feedback_type)
	  end
end

app/views/feedbacks/new.html.erb
<div class="container padding-top padding-bottom">
  <h2>Do you have anything for us? Let us know!</h2>
  <%= form_for @feedback, :url => feedbacks_path, html: { multipart: true } do |f| %>
    <% if @feedback.errors.any? %>
      <div id="error_explanation">
        <h4><b><%= pluralize(@feedback.errors.count, "error") %> non permettono al form di essere inviato</b></h4>
        <ul>
        <% @feedback.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="form-group">
          <%= f.label :feedback_type %>
          <%= f.select(:feedback_type, ['Feature Request', "Feedback", "Information"], {}, { :class => 'form-control' }) %>
        </div>
      </div>
      <div class="col-12">
        <div class="form-group">
          <%= f.label :message %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', class: "btn" %>
    </div>
  <% end %>
</div>