config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'
  devise_for :users,
              :controllers => {
                :omniauth_callbacks => 'omniauth_callbacks',
                :registrations => "users/registrations",
                invitations: "users/invitations"
              }

  devise_scope :user do
    get 'users/sign_out', :to => "devise/sessions#destroy"
  end


  root to: 'pages#home'
  get '/about', to: "pages#about"
  get '/terms-and-conditions', to: "pages#terms_and_conditions"
  get '/thank-you-for-the-sign-up', :to => "pages#sign_up_thank_you"
  get '/prelaunch_thank_you', :to => "pages#prelaunch_thank_you"
  get '/robots.:format' => 'pages#robots'
  get '/coming-soon' => 'pages#coming_soon'
  get '/apartments/search', :to => 'apartments#search', :defaults => { :format => 'js' }
  post '/apartments/:id/thank', :to => 'apartments#thank', :defaults => {:format => 'json'}

  resources :amenities
  resources :apartments
  resources :coworking_spaces
  resources :feedbacks
  resources :cities

  # namespace :admin do
  # 	get 'dashboard', :to => 'pages#dashboard'
  #   resources :amenities
  # 	resources :apartments
  # 	resources :coworking_spaces
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
include Geokit::Geocoders
class Apartment < ApplicationRecord
  has_many :associations, :dependent => :destroy
  has_many :amenities, through: :associations
  has_many :contacts
  has_many :pictures, :dependent => :destroy
  belongs_to :user
  belongs_to :wifi_speed
  belongs_to :city


  #after_create :assign_geometry
  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_mappable :default_units => :kms,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  #validates :name, :street, :city, :country, presence: true

  scope :by_amenities, ->(ids_ary) { joins(associations: :amenity).where("amenities.id" => ids_ary) }
  scope :by_city, -> (city_id) { where city_id: city_id }
  scope :by_wifi_speed, ->(wifi_speed) {joins(:wifi_speed).where('wifi_speeds.speed >= ?', wifi_speed)}
  scope :by_min_stay, ->(min_stay) {where min_stay: min_stay}
  scope :by_bedrooms, ->(bedrooms) {where "bedrooms >= ?", bedrooms}
  scope :by_type, ->(apartment_type) {where apartment_type: apartment_type}

  def assign_geometry
    begin
      lat = Apartment.geocode(self.address).lat.to_f
      lng = Apartment.geocode(self.address).lng.to_f
    rescue
      lat = Apartment.geocode(self.city.name).lat.to_f
      lng = Apartment.geocode(self.city.name).lng.to_f
    ensure
      self.lat = lat
      self.lng = lng
    end
  end
end

app/controllers/admin/apartments_controller.rb
class Admin::ApartmentsController < AdminController
	def index
		@apartments = Apartment.all
	end

	def new
		@apartment = Apartment.new
	end

	def create
		@apartment = Apartment.create(apartment_params)
		amenities = params[:apartment][:amenities]
		amenities.shift
		amenities.each do |amenity|
			@apartment.amenities.push Amenity.find(amenity)
		end
		@apartment.user = current_user

		respond_to do |format|
	      if @apartment.save
	      	if params[:images]
		        #===== The magic is here ;)
		        count = 0
		        params[:images].each { |image|
		          if count == 0
		            @apartment.pictures.create(image: image, apartment: @apartment, front: true)
		            count +=1
		          else @apartment.pictures.create(image: image, apartment: @apartment, front: false)
		          end
		        }
		    end
	        format.html { redirect_to admin_apartments_path, notice: 'apartment saved' }
	      else
	        format.html { render :new }
	      end
	    end
	end

	def show
		@apartment = Apartment.friendly.find(params[:id])
	end

	private

	def apartment_params
		params.require(:apartment).permit(:name, :street, :city, :country, :amenities, :phone_number, :email, :pictures)
	end
end

app/controllers/apartments_controller.rb
require "sendgrid-ruby"
include SendGrid
class ApartmentsController < ApplicationController
	before_filter :authenticate_user!, only: :new
	skip_before_action :verify_authenticity_token, only: :search
	before_action :is_the_owner, only: [:edit, :update]
	before_action :is_prelaunch, except: [:new, :create]
	def index
		if params[:lat] && params[:lng] && params[:city]
			if params[:lat] == "18.7060641" && params[:lng] == "98.98171630000002"
				lat = 18.8024267
				lng = 98.96718629999998
			else
				lat = params[:lat]
				lng = params[:lng]
			end
			@apartments = Apartment.within(10, :origin => [lat, lng]).all
			@city = params[:city]
		elsif params[:city]
			if params[:city] == "Chiang Mai"
				city =  "MAYA Lifestyle Shopping Center Chang Phueak Chiang Mai Thailand"
			else
				city = params[:city]
			end
			@city = params[:city]
			@apartments = Apartment.within(10, :origin => city)
		else
			@apartments = Apartment.where(:approved => true)
		end
		@cities = Apartment.where(:approved => true).map { |apartment| apartment.city.name }.uniq!
	end

	def new
		@apartment = Apartment.new
	end

	def thank
		@apartment = Apartment.friendly.find(params[:id])
		if cookies[:apt_thanked]
		  if !cookies[:apt_thanked].include?("apt-#{@apartment.id}")
		    @apartment.update_attributes(:thank_yous => @apartment.thank_yous + 1)
		    cookies[:apt_thanked]+="apt-#{@apartment.id}"
		    status = "Success"
		  else
		  	status = "Error"
		  end
		else
			@apartment.update_attributes(:thank_yous => @apartment.thank_yous + 1)
		    cookies[:apt_thanked]="apt-#{@apartment.id}"
		    status = "Success"
		end

		if @apartment.save
			respond_to do |format|
		      format.js { }
		      format.json {render json: {
		        :response => {
		        	:status => status,
		        	:thank_yous => @apartment.thank_yous
		        }
		      }}
			end
		end
	end

	def create
		@apartment = Apartment.create(apartment_params)
		if current_user
			@apartment.user = current_user
		else
			cookies[:invitation_email] = params[:invitation_email]
			@apartment.user = User.invite!(:email => params[:invitation_email]) do |u|
			  u.skip_invitation = true
			end
		end
		if params[:apartment][:home_owner] && params[:apartment][:home_owner] == "Yes"
			@apartment.home_owner = true
		else
			false
		end
		
		puts "///////////////////////"
		puts params[:apartment][:city]

		city = City.find_by_id params[:apartment][:city]

		if city
			@apartment.city = city
		else
			@apartment.city = City.create(name: params[:apartment][:city])
		end


		@apartment.description = params[:apartment][:description] if params[:apartment][:description]
		@apartment.wifi_speed = WifiSpeed.find_by_speed(params[:apartment][:wifi_speed])
		phone_number = params[:contact_phone]
		@apartment.contacts.push(Contact.create(:contact_type => "Phone Number", :value => phone_number))
		number_of_contacts = params[:contact_types].length
		number_of_contacts.times do |x|
		  @apartment.contacts.push(Contact.create(:contact_type => params[:contact_types][x], :value => params[:contact_values][x]))
		end
      	amenities = params[:apartment][:amenities]
		amenities.shift
		amenities.each do |amenity|
	  		@apartment.amenities.push Amenity.find(amenity)
		end

      	if params[:images]
	        first = true
	        params[:images].each { |image|
	          if first
	            @apartment.pictures.create(image: image, apartment: @apartment, front: true)
	            first = false
	          else
	          	@apartment.pictures.create(image: image, apartment: @apartment, front: false)
	          end
	        }
	    elsif params[:direct_uris]
	    	first = true
	        params[:direct_uris].each { |image|
	          if first
	            @apartment.pictures.create(direct_uri: image, apartment: @apartment, front: true)
	            first = false
	          else
	          	@apartment.pictures.create(direct_uri: image, apartment: @apartment, front: false)
	          end
	        }
	    end
		respond_to do |format|
	      	if @apartment.save
	      		send_user_email
	      		if current_user
				  format.html { redirect_to apartments_path, notice: 'apartment saved' }
				else
				  format.html { redirect_to prelaunch_thank_you_path, notice: 'apartment saved' }
				end
			else
		      	puts "/////////////////////////////////"
		      	puts @apartment.errors.details
		        format.html { render :new }
	      	end
	    end
	end

	def edit
	  @apartment = Apartment.friendly.find(params[:id])
	end

	def update
		@apartment = Apartment.friendly.find(params[:id])
		@apartment.update_attributes(apartment_params)
  		@apartment.wifi_speed = WifiSpeed.find_by_speed(params[:apartment][:wifi_speed])
  		@apartment.contacts.destroy_all
		number_of_contacts = params[:contact_types].length
		number_of_contacts.times do |x|
		  @apartment.contacts.push(Contact.create(:contact_type => params[:contact_types][x], :value => params[:contact_values][x]))
		end

      	amenities = params[:apartment][:amenities]
      	if amenities == [""]
      	  @apartment.amenities.destroy_all
      	end
		amenities.shift
		all_amenities = Amenity.all.map{|amenity| amenity.id}
		amenities = amenities.map{|amenity| amenity.to_i}
		diff = all_amenities - amenities
		amenities.each do |amenity|
	  	  if !@apartment.amenities.include?(Amenity.find_by_id(amenity))
	  		@apartment.amenities.push(Amenity.find_by_id(amenity))
	  	  end
		end

		if diff != []
		  diff.each do |x|
		  	if @apartment.amenities.include?(x)
		  	  @apartment.amenities.delete(x)
		  	end
		  end
		end
		respond_to do |format|

      	if params[:images]
      		@apartment.pictures.destroy_all
	        first = true
	        params[:images].each { |image|
	          if first
	            @apartment.pictures.push(Picture.create(image: image, apartment: @apartment, front: true))
	            first = false
	          else
	          	@apartment.pictures.push(Picture.create(image: image, apartment: @apartment, front: false))
	          end
	        }
	    elsif params[:direct_uris]
	    	@apartment.pictures.destroy_all
	    	first = true
	        params[:direct_uris].each { |image|
	          if first
	            @apartment.pictures.create(direct_uri: image, apartment: @apartment, front: true)
	            first = false
	          else
	          	@apartment.pictures.create(direct_uri: image, apartment: @apartment, front: false)
	          end
	        }
	    end
      	if @apartment.save
			format.html { redirect_to apartments_path, notice: 'apartment saved' }
		else
	      	puts "/////////////////////////////////"
	      	puts @apartment.errors.details
	        format.html { render :new }
      	end
	end
end
	def show
		@apartment = Apartment.friendly.find(params[:id])
	end

	def search
		# @apartments = Apartment.filter_result(params[:city], params[:amenities], params[:wifi_speed], params[:avg_price], params[:min_stay], params[:bedrooms], params[:apartment_type])
		if params[:city] && params[:city] == "Chiang Mai Thailand"
			params[:city] = "MAYA Lifestyle Shopping Center Chang Phueak Chiang Mai Thailand"
		end
		@apartments = Apartment.where(:approved => true)
		@apartments = @apartments.by_amenities(params[:amenities]) if params[:amenities]
		@apartments = @apartments.within(30, :origin => params[:city]).all if params[:city] != ""
		@apartments = @apartments.by_wifi_speed(params[:wifi_speed].to_i) if params[:wifi_speed]
		@apartments = @apartments.by_bedrooms(params[:bedrooms].to_i) if params[:bedrooms]
		@apartments = @apartments.by_type(params[:apartment_type]) if params[:apartment_type]
		#@apartments = @apartments.by_min_stay(params[:min_stay]) if params[:min_stay] != ""

		if params[:avg_price] && params[:avg_price] != "0"
	      @apartments = @apartments.reject {|a|
	      	a.avg_price.to_i > params[:avg_price].to_i
	      }
	    end

		respond_to do |format|
	      format.js { }
	      format.json {render json: {
	        :response => @apartments
	      }}
		end
	end

	private

	def is_the_owner
		unless current_user && current_user.admin? || current_user == Apartment.friendly.find(params[:id]).user
		  redirect_to apartment_path(Apartment.friendly.find(params[:id]))
		end
	end

	def is_prelaunch
		unless current_user || Time.now > "2017/08/01" || cookies[:has_account]
		  redirect_to root_path
		end
	end

	def send_user_email
	    if current_user
	      from = Email.new(email: "info@belooga.co")
	      to = Email.new(email: current_user.email)
	      subject = "[Belooga][Home Added] - You are awesome!"
	      email_text = "Hey, #{current_user.name} <br>"
	      email_text+= "Thanks for adding one of your favorite homes! We'll review it and publish it in the next 48 hours<br>"
	      email_text+= "Feel free to <a href='http://belooga.co/apartments/new'> keep adding new apartments </a> directly in the platform and help other people finding good places to stay.<br>"
	      email_text+= "Thank you!"
	      content = Content.new(type: "text/html", value: email_text)
	      mail = SendGrid::Mail.new(from, subject, to, content)
	      mail.template_id = '82ff248c-3492-481e-b8dc-6658c78db90d'
	      sg = SendGrid::API.new(api_key: ENV["SENDGRID_API_KEY"])
	      response = sg.client.mail._("send").post(request_body: mail.to_json)
	      puts response.status_code
	      puts response.body
	      puts response.headers
	    else
	      from = Email.new(email: cookies[:invitation_email])
	      to = Email.new(email: "info@belooga.co")
	      subject = "[Belooga][Home Added] - New Home Added By Early Adopter"
	      email_text = "Hey,<br>"
	      email_text+= "We have a new beta tester! Please review the apartment and approve it!<br>"
	      email_text+= "Thank you!"
	      content = Content.new(type: "text/html", value: email_text)
	      mail = SendGrid::Mail.new(from, subject, to, content)
	      mail.template_id = '82ff248c-3492-481e-b8dc-6658c78db90d'
	      sg = SendGrid::API.new(api_key: ENV["SENDGRID_API_KEY"])

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_contact.html.erb
<div class="col-md-3">
	<div class="form-group">
		<%= select_tag "contact_types[]", options_for_select(['Facebook Page','Website', "Email"], "Facebook Page"), class: "form-control", include_blank: true %>
	</div>
</div>
<div class="col-md-6">
	<div class="form-group">
		<%= text_field_tag "contact_values[]", nil, class: "form-control" %>
	</div>
</div>
<div class="col-md-1">
	<span class="btn btn-primary shadow add-contact-btn" data-toggle="tooltip" data-placement="top", title="Click to add more contact info"> <i class="fa fa-plus" aria-hidden="true"></i> </span>
</div>
<div class="col-md-2">
	<span class="btn btn-default shadow btn-next-section"> Next </span>
</div>

app/views/apartments/_direct_uri.html.erb
<div class="col-md-9">
	<div class="form-group">
		<%= text_field_tag "direct_uris[]", nil, class: "form-control" %>
	</div>
</div>
<div class="col-md-1">
	<span class="btn btn-primary shadow add-direct-uri-btn" data-toggle="tooltip" data-placement="top", title="Click to add more contact info"> <i class="fa fa-plus" aria-hidden="true"></i> </span>
</div>
<div class="col-md-2">
	<span class="btn btn-default shadow btn-next-section"> Next </span>
</div>

app/views/apartments/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = document.location.href;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = <%= @apartment.id %>; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://belooga.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<script id="dsq-count-scr" src="//belooga.disqus.com/count.js" async></script>

app/views/apartments/search.js.erb
$('.partial-container').html('<%= j render partial: "shared/list_container" %> <%= j render partial: "shared/map_container" %>');

app/views/apartments/show.html.erb
<% content_for :head do %>
  <title><%= @apartment.name %>, <%= @apartment.city.name %> | Belooga - Accommodations for digital nomads></title>
  <meta name="description" content="<%= @apartment.description %>"/>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA6Xw3W4DoiFJ_HvBgpcCMaz7KOEWivtUw"></script>
<% end %>

<div class="container">
  <div class="row">
    <% if current_user && current_user.admin? || current_user == @apartment.user %>
      <div class="col-1 offset-11 pull-right">
        <a href="<%= edit_apartment_path(@apartment)%>"><i class="fa fa-pencil-square" aria-hidden="true" style="margin-top: 30px; font-size: 38px;"></i></a>
      </div>
    <% end %>
    <div class="slider-container">
      <div id="apartment-slideshow" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <% (@apartment.pictures.length - 1).times do |i| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%= i+1 %>"></li>
        <% end %>
      </ol>
      <div class="carousel-inner" role="listbox">
        <% if @apartment.user %>
          <span class="uploaded-by-container">
            <% if current_user && current_user.admin? %>
              Uploaded By: <%= @apartment.user.email %>
            <% else %>
              Uploaded By: <%= @apartment.user.name %>
            <% end %>
            <% if @apartment.user.picture %>
              <img class="img-thumbnail" style="height:50px; width: 50px;" src="<%= @apartment.user.picture.image.url %>">
            <% end %>
          </span>
<!--           <span class="say-thanks" data-toggle="tooltip" data-placement="right", title='Say "Thanks" to <%= @apartment.user.name %>''>
              <i class="fa fa-thumbs-up" aria-hidden="true"></i><br>
          </span> -->
        <% end %>
        <div class="social-share-box">
          <div class="addthis_inline_share_toolbox_o5pu"></div>
        </div>
        <div class="addthis_inline_share_toolbox social-share-box"></div>
        <% if @apartment.pictures != [] %>
          <% @apartment.pictures.each do |picture|%>
            <% if picture.front? %>
              <div class="carousel-item active">
                <% if picture.direct_uri %>
                  <a href="<%= picture.direct_uri %>"  data-lightbox="apartment">
                    <div style="background-image: url('<%= picture.direct_uri %>'); background-size: cover; height: 100%; width: 100%;    background-position-y: bottom;"></div>
                  </a>
                <% else %>
                  <a href="<%= picture.image.url %>"  data-lightbox="apartment">
                    <div style="background-image: url('<%= picture.image.url %>'); background-size: cover; height: 100%; width: 100%;    background-position-y: bottom;"></div>
                  </a>
                <% end %>
              </div>
            <% else %>
              <div class="carousel-item">
                <% if picture.direct_uri %>
                  <a href="<%= picture.direct_uri %>"  data-lightbox="apartment">
                    <div style="background-image: url('<%= picture.direct_uri %>'); background-size: cover; height: 100%; width: 100%;    background-position-y: bottom;"></div>
                  </a>
                <% else %>
                  <a href="<%= picture.image.url %>"  data-lightbox="apartment">
                    <div style="background-image: url('<%= picture.image.url %>'); background-size: cover; height: 100%; width: 100%;    background-position-y: bottom;"></div>
                  </a>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <div class="carousel-item active">
            <a href="//s3.eu-west-2.amazonaws.com/belooga/Images/image-missing.png"  data-lightbox="apartment">
              <div style="background-image: url('//s3.eu-west-2.amazonaws.com/belooga/Images/image-missing.png'); background-size: cover; height: 100%; width: 100%;    background-position-y: bottom;"></div>
            </a>
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#apartment-slideshow" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#apartment-slideshow" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    </div>
  </div>
  <div class="row quick-info-bar shadow">
    <div class="col-4 text-center">
      <i class="fa fa-bed" aria-hidden="true"></i><br>
      <span><%= @apartment.bedrooms %> Beds</span>
    </div>
    <div class="col-4 text-center">
      <i class="fa fa-dollar" aria-hidden="true"></i><br>
      <span><%= @apartment.avg_price %>$/month</span>
    </div>
    <div class="col-4 text-center">
      <i class="fa fa-home" aria-hidden="true"></i><br>
      <span><%= @apartment.apartment_type %></span>
    </div>
  </div>
  <section class="apt-show-section">
    <div class="row">
      <div class="col-12">
        <h1 class="apartment-name">
          <%= @apartment.name %>
          <% if @apartment.wifi_speed %>
            <img class="rounded-circle" style="height:100px; width: auto;" src="<%= @apartment.wifi_speed.badge %>">
          <% end %>
          <% if @apartment.home_owner %>
            <img style="height:100px; width: auto;" src="https://farm5.staticflickr.com/4398/36296947521_2d6f00d98c_o.png">
          <% end %>
        </h1>
      </div>
      <div class="col-12">
        <span class="apartment-description"> <%= @apartment.description %> </span>
      </div>
    </div>
  </section>
  <section class="amenities-info apt-show-section">
    <div class="row">
      <div class="col-12 pull-left">
        <h4> Amenities</h4>
        <div class="row amenity-list">
          <% @apartment.amenities.each_with_index do |amenity, index| %>
            <div class="col-6 amenity">
              <span><i class="<%= amenity.icon %>"></i> &nbsp; <%= amenity.name %></span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <section class="workfrom apt-show-section">
    <div class="row">
      <div class="col-12 pull-left">
        <h4> Where To Work From </h4>
        <p> powered by <a href="//workfrom.com" target="_blank"> Workfrom.co </a></p>
      </div>
    </div>
  </section>
  <section class="contact-info apt-show-section">
    <div class="row">
      <div class="col-12 pull-left">
        <h4> Contact Details</h4>
      </div>
      </br>
      <div class="col-12 pull-left">
        <button class="btn btn-primary shadow" data-toggle="modal" data-target="#contact-modal" style="margin-top: 30px"> Show me how to contact the owner </button>
      </div>
    </div>
  </section>
  <section>
    <div class="row">
      <div class="col-12">
        <div id="map-canvas" class="text-center" style="height: 400px; margin-bottom: 30px; margin-top: 30px;">
      </div>
    </div>
  </section>
  <% if current_user %>
    <section>
      <div class="row">
        <div class="col-12">
          <%= render "disqus" %>
        </div>
      </div>
    </section>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header shadow text-center">
        <h6 class="modal-title" id="exampleModalLabel">Home owner contact details</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <div class="row">
          <div class="col-12 pull-left">
            <h5> <i class="fa fa-map-signs"></i> Address</h5>
          </div>
          <div class="col-12 pull-left">
            <p class="address"> <%= @apartment.address %></p>
          </div>
          <% @apartment.contacts.each do |contact| %>
            <div class="col-12 pull-left">
              <h5> <i class="<%= contact.icon %>"></i> <%= contact.contact_type %></h5>
            </div>
            <div class="col-12 pull-left">
              <%= contact.html.html_safe %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>




<script>
  var map;
  var address = "<%= @apartment.address %>";
  var geocoder = new google.maps.Geocoder();
  var mapOptions = {
    zoom: 8,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);


  geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      gifUrl="//s3.eu-west-2.amazonaws.com/belooga/Images/giphy.gif"
      let html = "<h4> Oops! Address Not Found!</h4>"
          html+= "<img src="+gifUrl+" style='height: 400px; width:400px;'>"
      $('#map-canvas').html(html);
    }
  });

  $("a[href='#map']").on('shown.bs.tab', function (e) {
    google.maps.event.trigger(map, 'resize');
  })
  $('#map-canvas').append('<a href="https://maps.google.co.uk/maps?saddr=current location&daddr=<%= @apartment.address %>" class=\'btn btn-primary btn-directions\' target=\'_blank\'>Need help getting there?</a>');

</script>